# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalink
# Site settings

Permalink: pretty
# relative_permalink: true

#setup 
title: Jekyll Demo
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nmenag.github.io/jekyll-demo/" # the base hostname & protocol for your site
baseurl: "/jekyll-demo"
twitter_username: nmenag
github_username:  nmenag


# Build settings
markdown: kramdown
sass:
    sass_dir: /assets/css/_sass
    style: compressed